### PR TITLE
partial addition of the Windows platform

### PR DESCRIPTION
**Pull request by julesgrc0**
## Windows Platform

> In summary
- Compilation with Visual Studio + configuration with VSCode (for Windows).
- Addition of Windows equivalents for Linux code.
- Addition of the "stdafx" file to group libraries.
- Compilation in C99 with union.
- Left todos and comments on unclear parts of the code.

> What I plan to do
- I will improve this version; I worked on it for 4 hours; it's an alpha version.
- I will add a testing system.

Let me know if the code suits you and if there's anything I can do to better adapt it to the initial project.
Thank you for your feedback, have a great day! (sorry for my english, i'm french )

### CODE REVIEW

**Comment by proh14** [comment]
Hello @julesgrc0, Thank you for your contribution. the code is good overall but one thing I noticed is you changed the formatting a bit, as discussed in contributing.md file this project uses the k&r coding style which is the default style for clang-format. I would be more than happy if you format the code, another thing is that for now i don't want to use VS solution files but maybe in the future I will so remove those for now.

**Comment by proh14** [comment]
Oh, and I forgot to say, can you please modify stdafx to get rid of some includes that are used? like time.h and stdarg and manually include them?

**Comment by julesgrc0** [comment]
Thanks for your feedback, I'll fix it tonight when I get home.

I wanted to know if I could change the structure of the project to make it easier to add other platforms in the future? For example, there would be a "platform" folder to add the different platforms, like this:

platform/win.h
platform/linux.h
platform/...

**Comment by proh14** [comment]
> Thanks for your feedback, I'll fix it tonight when I get home.
> 
> I wanted to know if I could change the structure of the project to make it easier to add other platforms in the future? For example, there would be a "platform" folder to add the different platforms, like this:
> 
> platform/win.h platform/linux.h platform/...

not now. Thank you for your contribution!

**Pull request merged**
